import { Inter, Montserrat } from 'next/font/google';
import './globals.css';
// import { WagmiConfig, createConfig, configureChains, polygonMumbai } from '@wagmi/core';
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers'
 
const inter = Inter({ subsets: ['latin'] });
 
// If loading a variable font, you don't need to specify the font weight
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
